trigger:
  - staging
  - trying
  - master
jobs:
  - job: Tox
    displayName: Tox
    pool:
        vmImage: ubuntu-20.04
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
      - script: python3 -m pip install -U tox
        displayName: Install tox
      - script: tox
        displayName: Run tox

  - job: Markdownlint
    displayName: Markdownlint
    pool:
        vmImage: ubuntu-20.04
    steps:
      - script: sudo npm install -g markdownlint-cli
        displayName: Install markdownlint-cli
      - script: markdownlint '**/*.md'
        displayName: Run markdownlint
